### ISSUE TITLE
windows环境下创建的模板运行报错

### ISSUE THREAD

**Issue by btea** [c7js/c7#1]
**问题**
在 `win10` 操作系统里，创建的模板仓库，运行会报错，内容如下。
![image](https://user-images.githubusercontent.com/24516654/119221235-f8a76680-bb20-11eb-8295-eac3609a0326.png)

**补充** 
经过检查测试，是在`script/create.js`里面使用`fs.readditSync`方法读取`src/runtime/components`目录下的文件名时返回的结果顺序导致的。
在 mac 环境下，返回的`_component.js`文件名在数组最前面，而在 windows 环境下，则是在数组的最后一个。这样就会导致代码在拼接的时候，将`class Component`拼接在最后，出现如图错误。

**Comment by c7js** [comment]
多谢呀 ! 我用更简单的方式修复啦~
