### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by anrananran** [c7js/c7#3]
1.富文本怎么实现
2.如何支持开发者工具对元素的选择
3.元素的z-index层叠顺序支持

**Comment by anrananran** [comment]
刚发现bug，input复制按Ctrl+C出现的
[![2jUhCT.png](https://z3.ax1x.com/2021/06/17/2jUhCT.png)](https://imgtu.com/i/2jUhCT)

**Comment by c7js** [comment]
富文本的实现还没有具体想过, 毕竟是个大坑.
打算自己实现一套开发者工具, 包括 元素选择 / 内容修改 / log 等, 敬请期待.
z-index 目前没有支持, 后续应该会加上.

这个 bug 应该是我没有处理 Control 键导致的, 应该是出现在 Windows 系统的 bug 吧. 很快会修复.
